<a href="https://colab.research.google.com/github/liliyakhabirova/Netology/blob/main/%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0_%D0%B3%D0%B8%D0%BF%D0%BE%D1%82%D0%B5%D0%B7_%D0%BD%D0%B0_%D0%B4%D0%B0%D1%82%D0%B0%D1%81%D0%B5%D1%82%D0%B5_%D0%BE%D0%B1_%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B5_%D0%B8%D0%B3%D1%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.**

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
df_game = pd.read_csv('https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/stat_case_study/vgsales.csv')
df_game

Name Platform  Year_of_Release         Genre  \
0                         Wii Sports      Wii           2006.0        Sports   
1                  Super Mario Bros.      NES           1985.0      Platform   
2                     Mario Kart Wii      Wii           2008.0        Racing   
3                  Wii Sports Resort      Wii           2009.0        Sports   
4           Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing   
...                              ...      ...              ...           ...   
16714  Samurai Warriors: Sanada Maru      PS3           2016.0        Action   
16715               LMA Manager 2007     X360           2006.0        Sports   
16716        Haitaka no Psychedelica      PSV           2016.0     Adventure   
16717               Spirits & Spells      GBA           2003.0      Platform   
16718            Winning Post 8 2016      PSV           2016.0    Simulation   

          Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  \
0          Nintendo     41.36     28.96      3.77         8.45         82.53   
1          Nintendo     29.08      3.58      6.81         0.77         40.24   
2          Nintendo     15.68     12.76      3.79         3.29         35.52   
3          Nintendo     15.61     10.93      3.28         2.95         32.77   
4          Nintendo     11.27      8.89     10.22         1.00         31.37   
...             ...       ...       ...       ...          ...           ...   
16714    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   
16715   Codemasters      0.00      0.01      0.00         0.00          0.01   
16716  Idea Factory      0.00      0.00      0.01         0.00          0.01   
16717       Wanadoo      0.01      0.00      0.00         0.00          0.01   
16718    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   

       Critic_Score  Critic_Count User_Score  User_Count Developer Rating  
0              76.0          51.0          8       322.0  Nintendo      E  
1               NaN           NaN        NaN         NaN       NaN    NaN  
2              82.0          73.0        8.3       709.0  Nintendo      E  
3              80.0          73.0          8       192.0  Nintendo      E  
4               NaN           NaN        NaN         NaN       NaN    NaN  
...             ...           ...        ...         ...       ...    ...  
16714           NaN           NaN        NaN         NaN       NaN    NaN  
16715           NaN           NaN        NaN         NaN       NaN    NaN  
16716           NaN           NaN        NaN         NaN       NaN    NaN  
16717           NaN           NaN        NaN         NaN       NaN    NaN  
16718           NaN           NaN        NaN         NaN       NaN    NaN  

[16719 rows x 16 columns]

In [ ]:
df_game.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Name             16717 non-null  object 
 1   Platform         16719 non-null  object 
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  object 
 4   Publisher        16665 non-null  object 
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       10015 non-null  object 
 13  User_Count       7590 non-null   float64
 14  Developer        10096 non-null  object 
 15  Rating           9950 non-null   object 
dtypes: float64(9), object(7)
memory usage: 2.0+ MB


In [ ]:
df_game['User_Score'].unique()

array(['8', nan, '8.3', '8.5', '6.6', '8.4', '8.6', '7.7', '6.3', '7.4',
       '8.2', '9', '7.9', '8.1', '8.7', '7.1', '3.4', '5.3', '4.8', '3.2',
       '8.9', '6.4', '7.8', '7.5', '2.6', '7.2', '9.2', '7', '7.3', '4.3',
       '7.6', '5.7', '5', '9.1', '6.5', 'tbd', '8.8', '6.9', '9.4', '6.8',
       '6.1', '6.7', '5.4', '4', '4.9', '4.5', '9.3', '6.2', '4.2', '6',
       '3.7', '4.1', '5.8', '5.6', '5.5', '4.4', '4.6', '5.9', '3.9',
       '3.1', '2.9', '5.2', '3.3', '4.7', '5.1', '3.5', '2.5', '1.9', '3',
       '2.7', '2.2', '2', '9.5', '2.1', '3.6', '2.8', '1.8', '3.8', '0',
       '1.6', '9.6', '2.4', '1.7', '1.1', '0.3', '1.5', '0.7', '1.2',
       '2.3', '0.5', '1.3', '0.2', '0.6', '1.4', '0.9', '1', '9.7'],
      dtype=object)

In [ ]:
df_game['User_Score'] = df_game['User_Score'].replace('tbd', np.nan)
df_game['User_Score'].unique()

array(['8', nan, '8.3', '8.5', '6.6', '8.4', '8.6', '7.7', '6.3', '7.4',
       '8.2', '9', '7.9', '8.1', '8.7', '7.1', '3.4', '5.3', '4.8', '3.2',
       '8.9', '6.4', '7.8', '7.5', '2.6', '7.2', '9.2', '7', '7.3', '4.3',
       '7.6', '5.7', '5', '9.1', '6.5', '8.8', '6.9', '9.4', '6.8', '6.1',
       '6.7', '5.4', '4', '4.9', '4.5', '9.3', '6.2', '4.2', '6', '3.7',
       '4.1', '5.8', '5.6', '5.5', '4.4', '4.6', '5.9', '3.9', '3.1',
       '2.9', '5.2', '3.3', '4.7', '5.1', '3.5', '2.5', '1.9', '3', '2.7',
       '2.2', '2', '9.5', '2.1', '3.6', '2.8', '1.8', '3.8', '0', '1.6',
       '9.6', '2.4', '1.7', '1.1', '0.3', '1.5', '0.7', '1.2', '2.3',
       '0.5', '1.3', '0.2', '0.6', '1.4', '0.9', '1', '9.7'], dtype=object)

In [ ]:
df_game['Year_of_Release'] = df_game['Year_of_Release'].astype('Int64')
df_game['User_Count'] = df_game['User_Count'].astype('Int64')
df_game['User_Score'] = df_game['User_Score'].astype('float64')
df_game['Critic_Count'] = df_game['Critic_Count'].astype('Int64')


df_game['User_Score'] = df_game['User_Score'] * 10

In [ ]:
df_game.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Name             16717 non-null  object 
 1   Platform         16719 non-null  object 
 2   Year_of_Release  16450 non-null  Int64  
 3   Genre            16717 non-null  object 
 4   Publisher        16665 non-null  object 
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   Int64  
 12  User_Score       7590 non-null   float64
 13  User_Count       7590 non-null   Int64  
 14  Developer        10096 non-null  object 
 15  Rating           9950 non-null   object 
dtypes: Int64(3), float64(7), object(6)
memory usage: 2.1+ MB


Проверка гипотезы: Как критики относятся к спортивным играм?
*  Н0 - Критики ставят спортивным играм более высокие оценки
*  Н1 - Оценки критиков спортивным играм не отличаются от оценок игр других жанров

Сначала проверим данные на нормальность распределения с помощью теста Шапиро-Уилка

In [ ]:
import scipy.stats as st

In [ ]:
df_score = df_game['Critic_Score'].dropna()
df_score

0        76.0
2        82.0
3        80.0
6        89.0
7        58.0
         ... 
16700    61.0
16701    53.0
16702    48.0
16706    60.0
16709    63.0
Name: Critic_Score, Length: 8137, dtype: float64

In [ ]:
df_score = df_score.to_numpy()

In [ ]:
stat, p = st.shapiro(df_score)

print('stat=%.3f, p=%.3f' % (stat, p))
if p > 0.05:
    print('Вероятно нормальное распределение')
else:
    print('Вероятно не нормальное распределение')

stat=0.974, p=0.000
Вероятно не нормальное распределение


Распределение вероятно не нормальное, для проверки гипотезы используем Тест Манна-Уитни

In [ ]:
df_game['Critic_Score']

0        76.0
1         NaN
2        82.0
3        80.0
4         NaN
         ... 
16714     NaN
16715     NaN
16716     NaN
16717     NaN
16718     NaN
Name: Critic_Score, Length: 16719, dtype: float64

In [ ]:
all = df_game['Critic_Score'].dropna()
all

0        76.0
2        82.0
3        80.0
6        89.0
7        58.0
         ... 
16700    61.0
16701    53.0
16702    48.0
16706    60.0
16709    63.0
Name: Critic_Score, Length: 8137, dtype: float64

In [ ]:
sport = df_game[df_game['Genre'] == 'Sports']['Critic_Score'].dropna()
sport

0        76.0
3        80.0
13       80.0
15       80.0
77       82.0
         ... 
16456    78.0
16478    57.0
16532    78.0
16550    78.0
16555    88.0
Name: Critic_Score, Length: 1194, dtype: float64

In [ ]:
stat, p = st.mannwhitneyu(all, sport)

print(f"Статистика = {stat:.5f}, p = {p:.5f}")

if p > 0.05:
    print('Не отклоняем нулевую гипотезу, распределения, вероятно, одинаковые')
else:
    print('Отклоняем нулевую гипотезу, распределения, вероятно, различаются')

Статистика = 4163630.50000, p = 0.00000
Отклоняем нулевую гипотезу, распределения, вероятно, различаются


In [ ]:
print(sport.mean(), all.mean())

71.96817420435511 68.96767850559173


Вывод: Распределение отличается, возможно, критикам больше нравятся спортивные игры

Проверка гипотезы: Критикам нравятся больше игры на PC или на PS4?

*   Н0 - Оценки критиков игр на PC и PS4 не отличаются
*   Н1 - Оценки критиков игр на PC и PS4 статистически отличаются


In [ ]:
df_pc = df_game[df_game['Platform'] == 'PC']['Critic_Score'].dropna()

In [ ]:
df_ps4 = df_game[df_game['Platform'] == 'PS4']['Critic_Score'].dropna()

In [ ]:
stat, p = st.mannwhitneyu(df_pc, df_ps4)

print(f"Статистика = {stat:.5f}, p = {p:.5f}")

if p > 0.05:
    print('Не отклоняем нулевую гипотезу, распределения, вероятно, одинаковые')
else:
    print('Отклоняем нулевую гипотезу, распределения, вероятно, различаются')

Статистика = 106906.50000, p = 0.00001
Отклоняем нулевую гипотезу, распределения, вероятно, различаются


In [ ]:
print(df_pc.mean(), df_ps4.mean())

75.92867132867133 72.09126984126983


Вывод: Оценки критиков игр на PC и PS4 статистически отличаются, возможно критикам больше нравятся игры на PC

Проверка гипотезы: Критикам больше нравятся стрелялки или стратегии?

*   Н0 - Распределение данных статистически не отличается
*   Н1 - Распределение данных статистически отличается



In [ ]:
df_shooter = df_game[df_game['Genre'] == 'Shooter']['Critic_Score'].dropna()

In [ ]:
df_strategy = df_game[df_game['Genre'] == 'Strategy']['Critic_Score'].dropna()

In [ ]:
stat, p = st.mannwhitneyu(df_shooter, df_strategy)

print(f"Статистика = {stat:.5f}, p = {p:.5f}")

if p > 0.05:
    print('Не отклоняем нулевую гипотезу, распределения, вероятно, одинаковые')
else:
    print('Отклоняем нулевую гипотезу, распределения, вероятно, различаются')

Статистика = 136251.50000, p = 0.24754
Не отклоняем нулевую гипотезу, распределения, вероятно, одинаковые


In [ ]:
print(df_shooter.mean(), df_strategy.mean())

70.18114406779661 72.08609271523179


Вывод: Оценки критиков игр шутеров и стратегий статистически отличаются, возможно критикам больше нравятся стратегии

**2.**

In [ ]:
df_message = pd.read_csv('https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/stat_case_study/spam.csv')
df_message

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
df_message['Message'] = df_message['Message'].str.lower()
df_message

Category                                            Message
0         ham  go until jurong point, crazy.. available only ...
1         ham                      ok lar... joking wif u oni...
2        spam  free entry in 2 a wkly comp to win fa cup fina...
3         ham  u dun say so early hor... u c already then say...
4         ham  nah i don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  this is the 2nd time we have tried 2 contact u...
5568      ham               will ü b going to esplanade fr home?
5569      ham  pity, * was in mood for that. so...any other s...
5570      ham  the guy did some bitching but i acted like i'd...
5571      ham                         rofl. its true to its name

[5572 rows x 2 columns]

In [ ]:
df_message['Message'] = df_message['Message'].replace(to_replace ='[\W_]+', value = ' ', regex = True)
df_message['Message']

0       go until jurong point crazy available only in ...
1                                ok lar joking wif u oni 
2       free entry in 2 a wkly comp to win fa cup fina...
3            u dun say so early hor u c already then say 
4       nah i don t think he goes to usf he lives arou...
                              ...                        
5567    this is the 2nd time we have tried 2 contact u...
5568                 will ü b going to esplanade fr home 
5569    pity was in mood for that so any other suggest...
5570    the guy did some bitching but i acted like i d...
5571                            rofl its true to its name
Name: Message, Length: 5572, dtype: object

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stopwords_set = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download('omw-1.4')
nltk.download('wordnet')

wordnet_lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package wordnet to /root/nltk_data...


In [ ]:
def stop_lem(row):
  str_ = ''
  for word in row['Message'].split():
    if word not in stopwords_set:
      word = wordnet_lemmatizer.lemmatize(word)
      str_ += word + ' '
  return str_

In [ ]:
df_message.apply(stop_lem, axis=1)

0       go jurong point crazy available bugis n great ...
1                                ok lar joking wif u oni 
2       free entry 2 wkly comp win fa cup final tkts 2...
3                    u dun say early hor u c already say 
4                    nah think go usf life around though 
                              ...                        
5567    2nd time tried 2 contact u u 750 pound prize 2...
5568                         ü b going esplanade fr home 
5569                                pity mood suggestion 
5570    guy bitching acted like interested buying some...
5571                                      rofl true name 
Length: 5572, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df_message['Message'])
names = tfidf.get_feature_names_out()
tfidf_matrix = pd.DataFrame(tfidf_matrix.toarray(), columns=names)

In [ ]:
tfidf_matrix

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0     0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0   
1     0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0   
2     0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0   
3     0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0   
4     0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0   
...   ...  ...     ...           ...   ...   ...          ...          ...   
5567  0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0   
5568  0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0   
5569  0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0   
5570  0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0   
5571  0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0   

      0125698789   02  ...  zhong  zindgi  zoe  zogtorius  zoom  zouk  zyada  \
0            0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0   
1            0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0   
2            0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0   
3            0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0   
4            0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0   
...          ...  ...  ...    ...     ...  ...        ...   ...   ...    ...   
5567         0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0   
5568         0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0   
5569         0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0   
5570         0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0   
5571         0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0   

       èn   ú1  〨ud  
0     0.0  0.0  0.0  
1     0.0  0.0  0.0  
2     0.0  0.0  0.0  
3     0.0  0.0  0.0  
4     0.0  0.0  0.0  
...   ...  ...  ...  
5567  0.0  0.0  0.0  
5568  0.0  0.0  0.0  
5569  0.0  0.0  0.0  
5570  0.0  0.0  0.0  
5571  0.0  0.0  0.0  

[5572 rows x 8707 columns]

In [ ]:
df_message['Category'] = df_message['Category'].replace('ham', 1)
df_message['Category'] = df_message['Category'].replace('spam', 0)

In [ ]:
df_message

Category                                            Message
0            1  go until jurong point crazy available only in ...
1            1                           ok lar joking wif u oni 
2            0  free entry in 2 a wkly comp to win fa cup fina...
3            1       u dun say so early hor u c already then say 
4            1  nah i don t think he goes to usf he lives arou...
...        ...                                                ...
5567         0  this is the 2nd time we have tried 2 contact u...
5568         1               will ü b going to esplanade fr home 
5569         1  pity was in mood for that so any other suggest...
5570         1  the guy did some bitching but i acted like i d...
5571         1                          rofl its true to its name

[5572 rows x 2 columns]

In [ ]:
y = df_message['Category'].to_numpy()
y

array([1, 1, 0, ..., 1, 1, 1])

6) Разделите данные на тестовые и тренировочные в соотношении 30/70, укажите random_state=42. Используйте train_test_split;
7) Постройте модель логистической регрессии, укажите random_state=42, оцените ее точность на тестовых данных;
8) Опишите результаты при помощи confusion_matrix;
9) Постройте датафрейм, который будет содержать все исходные тексты сообщений, классифицированные неправильно (с указанием фактического и предсказанного).

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix, y, test_size=0.3, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(X_train, y_train)

LogisticRegression()

In [ ]:
lr.predict(X_test)

array([1, 1, 1, ..., 1, 0, 1])

In [ ]:
result = pd.DataFrame([y_test, lr.predict(X_test)]).T
result

0  1
0     1  1
1     1  1
2     1  1
3     1  1
4     1  1
...  .. ..
1667  1  1
1668  0  0
1669  1  1
1670  0  0
1671  1  1

[1672 rows x 2 columns]

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
y_true = result[0].to_numpy()
y_true

array([1, 1, 1, ..., 1, 0, 1])

In [ ]:
y_pred = result[1].to_numpy()
y_pred

array([1, 1, 1, ..., 1, 0, 1])

In [ ]:
confusion_matrix(y_true, y_pred)

array([[ 165,   59],
       [   2, 1446]])